version: '3'

services:
  app:
    container_name: ref-style
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      npm_default:
        ipv4_address: 172.18.0.32

networks:
  npm_default:
    external: true